---
abstract: 'munge the Bash PATH environment variable'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires:
  Test::Differences: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.58
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-pathed
no_index:
  directory:
    - t
    - inc
requires:
  Getopt::Long: 0
  Pod::Find: 0
  Pod::Usage: 0
version: 0.04
